RedHatInsights/cicd-tools

- cji_smoke_test.sh
If there is an iqe-tests image tag with the corresponding PR number and app name use it instead of the default app image tag.
> Check for the existence of PR specific IQE_IMAGE_TAG

- cji_smoke_test.sh
pass the options fron clowder CJI to bonfire.
Refer : https://github.com/RedHatInsights/clowder/pull/842 ,  https://github.com/RedHatInsights/clowder/pull/802 and https://github.com/RedHatInsights/bonfire/pull/319
> Adds missing iqe options to smoke test script

- _common_deploy_logic.sh
- deploy_ephemeral_env.sh
We have multiple clowdapp files in [ros-ocp repo](https://github.com/RedHatInsights/ros-ocp-backend) and want that when PR check runs bonfire should refer both the clowdapp file from the PR commit.
> Set multiple template-ref while running bonfire

- README.md
- docs/cicd_tools/container_lib.md
- docs/cicd_tools/image_builder.md
- src/shared/image_builder_lib.sh
- test/shared_image_builder_lib.bats
This changes the current behavior to:
- Always push and create all the tags (previously on CI context it would only push / create the main tag)
- Override the default "git hash tag" with a user-chosen tag.
> Support default tag updates

- deploy_ephemeral_env.sh
Sometimes our `pr_check` can take over an hour so we need the option to reserve the namespace for longer.
> Add the option to change bonfire reservation duration

- cji_smoke_test.sh
Ticket: https://issues.redhat.com/browse/RHCLOUD-28568
This PR makes sure the Junit tests pass by checking the artifacts exist.
> Ensure JUnit tests pass

- cji_smoke_test.sh
Adds support to pass '--env-var' args to `bonfire deploy-iqe-cji` when running the smoke test. Related to https://github.com/RedHatInsights/bonfire/pull/331
> Support for using '--env-var' when running IQE CJI

- bootstrap.sh
This PR provides a proper error message when credentials are not found when attempting to log into a cluster
Now the output in case all login attempt are unsuccessful should look like this
```
OC_LOGIN_SERVER=foo OC_LOGIN_TOKEN=bar source bootstrap.sh 
error: dial tcp: lookup foo: no such host - verify you have provided the correct host and port and that the server is currently running.
Failed logging into cluster: 'ephemeral'
Environment variables for cluster 'crcd' not found
Failed logging into any cluster!
```
> Add login to Openshift cluster logic

- _common_deploy_logic.sh
- bootstrap.sh
Store .docker, .kube, and .bonfire in a tmp dir so they are not part of the content in $WORKSPACE
> Use a job tmp dir instead of WORKSPACE

- _common_deploy_logic.sh
- bootstrap.sh
I suspect trap_proxy is causing some unexpected behavior when it comes to "overwriting" a trap... currently we call: 
* `trap_proxy job_cleanup EXIT ERR SIGINT SIGTERM` in bootstrap.sh
* and `trap_proxy teardown EXIT ERR SIGINT SIGTERM` in _common_deploy_logic.sh
but in Jenkins we see evidence of the job_cleanup running *before* the teardown runs:
```
+++ job_cleanup ERR
+++ local CAPTURED_SIGNAL=ERR
+++ echo 'triggering job cleanup due to signal: ERR'
triggering job cleanup due to signal: ERR
+++ rm -fr /var/lib/jenkins/jenkins-insights-platform-advisor-backend-smoke-test-master-19085-dHySbX
+ teardown EXIT
+ '[' 0 -ne 0 ']'
+ local CAPTURED_SIGNAL=EXIT
```
This doesn't make sense ... my understanding is that we should be re-setting the trap handler for all of these signals -- I would …
> Remove trap_proxy

- .github/workflows/tests.yml
- .gitmodules
- Dockerfile
- README.md
- test/generate_coverage.sh
- test/shared_image_builder.bats
- Updates tests for the eventual addition of a Dockerfile to the repo. The tests assumed no Dockerfile existed but this would break them should a Dockerfile is added
- Adds `bats` as a submodule for locally running tests
also unblocks https://github.com/gbenhaim/cicd-tools/pull/15
> feat(tests): prepare tests for adding Dockerfile

- bootstrap.sh
- build.sh
- deploy_ephemeral_db.sh
- deploy_ephemeral_env.sh
- examples/backend-pipeline-pr-checks/Jenkinsfile
- examples/frontends-pipeline-pr-checks/iqe_tests.sh
- examples/pr_check_template.sh
- examples/unit_test_example_ephemeral_db.sh
- smoke_test.sh
This PR aims to refactor the usage of different variables for relative working dir paths 
- Uses APP_ROOT as WORKSPACE when defined, else current working directy
- Removes  explicit use of WORKSPACE 
- Removes BONFIRE_ROOT, CICD_ROOT, replaces with CICD_TOOLS_DIR
> refactor(ci): refactor bootstrap paths

- image_build_scripts/install_system_dependencies.sh
`pip3` is 3.9 version, which was also installing Python 3.9.
This installs the correct `pip` version, and configures `python3` and `pip3` links for the Python `3.11` version.
> fix(python): fixes python3 and pip3 installation

- bootstrap.sh
- frontends/Jenkinsfile
- this PR adds a flag to control whether if IMAGE_TAG  gets forcibly set or not. 
- Now the original behavior is restored, and `IMAGE_TAG` will be always set by the `bootsrap.sh` script. 
- One can avoid this behavior and set `PRESERVE_IMAGE_TAG` to a non empty value to keep the pre-existing `IMAGE_TAG` value.
- this is to avoid regressions after #19 was merged, where this behavior was changed to force the `IMAGE_TAG` preservation if it was already defined.
> feat: add flag to control IMAGE_TAG overwrite behavior

- bootstrap.sh
- frontends/cypress_component_tests.sh
- frontends/cypress_e2e_tests.sh
- src/shared/image_builder.sh
- test/shared_image_builder.bats
So that if any tool has set it before our jobs begin, it will be overwritten and match DOCKER_CONFIG
> Set REGISTRY_AUTH_FILE env var

- bootstrap.sh
- build.sh
- src/shared/image_builder.sh
- test/shared_image_builder.bats
Hi! This PR changes the usage of `gitlabMergeRequestId` to `gitlabMergeRequestIid`. I've been seeing failures in the `runtimes-inventory` jenkins pipeline, and I've narrowed it down to the failure to: https://github.com/RedHatInsights/cicd-tools/blob/main/bootstrap.sh#L33
From taking a look through the gitlab api and jenkins gitlab plugin documention, it appears that Id is not the same as Iid. If we're looking for the id of a specific merge request to use in an image tag for example like pr-215-5ff8174, the 215 here is the Iid. The id looks to refer to a more global merge request Id, while the Iid is Internal ID for the merge request. This PR changes the Id usage in this repo to use Iid instead.
In the `runtimes-inventory` pipeline we have two images that need to be built, …
> Fix gitlab merge request id usage

- cji_smoke_test.sh
The docker inspect command was errored out when trying to inspect IQE tagged images.I think the more appropriate way would be just to check the tags and see if the IQE tagged image is present. 
Error:
```
podman manifest inspect quay.io/cloudservices/iqe-tests:rhsm-subscriptions-pr-3554 -v
Error: getting content of manifest list or image quay.io/cloudservices/iqe-tests:rhsm-subscriptions-pr-3554: parsing manifest blob "{\"schemaVersion\":2,\"mediaType\":\"application/vnd.oci.image.manifest.v1+json\",\"config\":{\"mediaType\":\"application/vnd.oci.image.config.v1+json\",\"digest\":\"sha256:3ec73021fd3583315ff78c5005c9dd6ca1903a8feab0380d63392a3aee293686\",\"size\":12393},\"layers\":[{\"mediaType\":\"application/vnd.oci.image.layer.v1.tar+gzip\",\"digest\":\"sha256:13d626b04f00b85307f9a72d61 …
```
> Use docker search instead of manifest inspect to check for tagged IQE images

- cji_smoke_test.sh
We are working on adding floorist plugin tests to the pr_check process for policies. We have a working implementation using 2 cji jobs but they are both named the same. We need to ability to overwrite the cji name via an environment variable. This is a pattern that is already done with several items inside of cji_smoke_test.sh . We just need to extend this functionality to CJI_NAME.
> Add support for $IQE_CJI_NAME to populate CJI_NAME when given

- konflux_scripts/deploy-iqe-cji.sh
This was leaving empty quotes in the final command if unset: `bonfire deploy-iqe-cji playbook-dispatcher --marker smoke --filter '' --image-tag '' --requirements '' --requirements-priority '' --test-importance '' --plugins playbook-dispatcher --env clowder_smoke --cji-name playbook-dispatcher --namespace ephemeral-geupva ''`
> Fix double quotes, and unset at the source.

- frontends/lint.sh
`docker/podman cp .` is copying the parent directory as well as the contents of the current directory.  The scripts are only expecting the contents of the current directory.  Switching it to `docker cp . `.
curiousity-frontend is using these scripts.
> fix: update docker/podman cp . syntax for newer version.
